### ISSUE TITLE
Orbitals look weird.

### ISSUE THREAD

**Issue by ghost** [cgnieder/chemmacros#44]
<img width="309" alt="Screen Shot 2021-05-22 at 4 40 46 PM" src="https://user-images.githubusercontent.com/42444945/119240269-7fa61000-bb1c-11eb-9338-b3ef7f95c904.png">
Using new 2021 versions of packages. Is there an issue with Tikz?

**Comment by TheDeepestSpace** [comment]
I'm also facing the same issue. It seems like shading of a closed Bezier curve created through `controls` does not work as expected. If I move the final coordinate by a tiny bit to break the loop, it starts clipping the shading background properly. 

Here's the part of the code that I am modifying to fix `p` orbitals for example:
https://github.com/cgnieder/chemmacros/blob/c78f3e55a9da13184b165e2be903e9ccb28c940a/code/chemmacros.orbital.code.tex#L186-L201
that is, if I change `.. (0pt,0pt)` to `.. (0.0001pt,0pt)` the shading works as expected. The same has to be done for the rest of the orbitals that use `controls` (`s` orbital works fine).

This is an ugly workaround, but it does seem like the issue is related to tikz.

I'm also using TexLive 2021, with `chemmacros 5.11a` and `pgf 3.1.9a`

**Comment by cgnieder** [comment]
I can't reproduce the issue. Using an up to date TL2021 this MWE

```latex
\documentclass{article}

\usepackage{chemmacros}
\usechemmodule{orbital}
\begin{document}

\orbital{s} \orbital{p} \orbital{sp} \orbital{sp2} \orbital{sp3}

\end{document}
```

gives

![grafik](https://user-images.githubusercontent.com/2248538/148836516-ee039f04-d641-479c-8051-e3e416d64079.png)

------

Can you provide code to reproduce the “weird” orbitals?

**Comment by jckoester** [comment]
That exact MWE gives me this on a current texlive 2023 (chemmacros 6.2a):
![grafik](https://github.com/cgnieder/chemmacros/assets/777345/c5691657-3309-4e5b-b57e-62a5ba67dd11)

The changes suggested by [[TheDeepestSpace](https://github.com/TheDeepestSpace)](https://github.com/cgnieder/chemmacros/issues/44#issuecomment-999214282) fixed it for me as well.

**Comment by wiobber** [comment]
The problem still exists, but only with certain PDF viewers.
E.g. with chrome, or Vscode default viewers.
![image](https://github.com/cgnieder/chemmacros/assets/9051688/6f723d8a-72f0-4c00-ade7-e282b55c954c)
