### ISSUE TITLE
Stereochemistry: \cip locants should not be printed in italics

### ISSUE THREAD

**Issue by tstone-1** [cgnieder/chemmacros#45]
The manual says:
![2021-07-09](https://user-images.githubusercontent.com/48162401/125058572-b32c0200-e0aa-11eb-8778-6a3f3758ee4c.png)

I'm pretty sure™ that (_2S_,_3S_) and (_2E_,_4Z_) should be (2_S_,3_S_) and (2_E_,4_Z_) instead, respectively, so that the locant numbers are printed in roman. [This resource](http://publications.iupac.org/pac/1976/pdf/4501x0011.pdf) seems to confirm my opinion, see page 17 and 19, for example.

**Comment by Sonja-K** [comment]
The 2013 version of the IUPAC Blue book, sepcifically "Chapter P-9 SPECIFICATION OF CONFIGURATION AND CONFORMATION" seems to agree on that (https://www.qmul.ac.uk/sbcs/iupac/BlueBook/PDF/P9.pdf)

`chemmacros`' `nomenclature` module offers several options to alter the format of entries inside of `\cip`. Among these, is also `cip-number-format ` which you could use to get the expected behaviour: italic letters and upright numbers:

![dsfsdfesf](https://user-images.githubusercontent.com/30843621/126880073-ea41f639-08ed-45b0-b1ef-3f613c312a62.png)


```
\documentclass{article}
\usepackage{chemmacros}
\chemsetup{modules=nomenclature}
\chemsetup{nomenclature/cip-number-format=\normalfont}
\begin{document}

\iupac{\cip{2S,3S}-Wein|s\"aure}\par
\iupac{\cip{2S,3R}-($-$)-2,3,4-Tri|hydroxy|butanal}\par
\iupac{\cip{2E,4Z}-Hexa|diene}

\end{document}
```

**Comment by cgnieder** [comment]
This should be the default behavior, changed for the next update.
