### ISSUE TITLE
Warning for \isotope command

### ISSUE THREAD

**Issue by wehro** [cgnieder/chemmacros#47]
I get a warning message with the following document. The output is however correct.
```
\documentclass{article}
\usepackage{chemmacros}
\usepackage{textgreek}

\begin{document}
\ch{\isotope{U} ->[\textalpha] \isotope{234,Th} ->[\textbeta] \isotope{234,Pa} ->[\textbeta] \isotope{234,U}}
\end{document}
```
```
Package chemmacros Warning: The isotope \chemformula_subscript:n
(chemmacros)                {2}\chemformula_subscript:n
(chemmacros)                {3}\chemformula_subscript:n {4} is not defined for
(chemmacros)                element Th.

```

**Comment by cgnieder** [comment]
You are using this within `\ch{}` (from the package [`chemformla`](https://github.com/cgnieder/chemformula)). Outside of it you don't get warnings.

Inside of `\ch{}` numbers are treated as stoichiometric factors or subscripts:

```latex
\ch{1/2 H2O}
```
![grafik](https://user-images.githubusercontent.com/2248538/150864757-cbee322a-0002-4880-a3ed-db630b06d63f.png)

That fact that your example doesn't give errors is merely by chance. In order to give the correct results here you need to hide the numbers from the parser by surrounding the inputs with `"..."`:

```latex
\ch{\isotope{U} ->[\textalpha] "\isotope{234,Th}" ->[\textbeta] "\isotope{234,Pa}" ->[\textbeta] "\isotope{234,U}"}
```
